# Generated by Django 4.2.11 on 2024-05-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='about',
        ),
    ]
